progressbar.go
see [Go 1.9 Release Notes](https://golang.org/doc/go1.9)
Duration.Round only supported in go1.9
=> fix remove Duration.Round to compatible with version less than go1.9

progressbar.go
This commit adds the `OptionSetDescription` function, which specifies a string to render in front of the progress bar.
It also adds the `SaucerHead` field to the `Theme` struct, which allows for the rightmost part of the saucer to be a different character than the others.
This is useful for arrow-like progress bars, as I use them in one of my projects:
Both of these changes are 100% backwards-compatible, so the behaviour of existing projects does not change - if the `SaucerHead` field is empty, the value of `Saucer` is used for the saucer head.
=> Added Description and SaucerHead features

README.md, progressbar.go
The main reason for this commit was to add a proper `Clear()` function, so we don't have to write a bunch of spaces to the output in case the progress bar has gotten shorter.
This brings the huge advantage of being able to use up to 12 more characters before the progress bar introduces a line break.
It works by keeping track of the maximum width the progress bar ever reached, and simply overwriting the current line with an equal amount of spaces.
Now since I use ANSI color codes in my own progress bars, simply getting the string length and subtracting the carriage return is not sufficient for me, as the ANSI escape codes do not take up actual space in the console output. Therefore, I'm using a regex to remove any ANSI escape codes from the string used to count the line width.
Since I …
=> Added support for color codes and a proper Clear() function

progressbar.go
I screwed up in the previous PR - when using color codes, I'm using the string with the original color codes (`[cyan]`) etc for line width calculation, but we need to use the string that is actually going to be output for line width calculation.
Sorry :(
=> Use the color-transformed string for line width detection

progressbar.go
Two reasons for this PR:
1. No usage of `RLock`/`RUnlock` methods
2. https://github.com/golang/go/issues/17973
=> Prefer Mutex to RWmutex

progressbar.go, progressbar_test.go
The ability to display iterations per second in the progress bar is great but generic. I'd like to be able to customize that string to make it refer to whatever thing I'm actually doing. For examples, downloads per second or renders per second.
This PR enables a custom string to be used for it/s.
I implemented it as its own option in order to maintain backwards compatibility. Ideally it would be been a parameter for OptionShowIts() to keep things simple.
I also added a test to verify the original functionality as well as the new custom string.
=> Allow custom it/s string.

progressbar.go
Finish will set the `p.state.currentNum` to `p.config.max`:
```go
// Finish will fill the bar to full
func (p *ProgressBar) Finish() error {
p.lock.Lock()
p.state.currentNum = p.config.max
p.lock.Unlock()
return p.Add(0)
}
```
Then, it calls `Add()`, which however alters the `p.state.currentNum`:
```go
if p.config.ignoreLength {
p.state.currentNum = (p.state.currentNum + num) % p.config.max
} else {
p.state.currentNum += num
}
```
For spinners, this will cause the bar to never reach `p.config.max`, so the `p.config.onCompletion` will never be called in `render()`:
```go
// check if the progress bar is finished
if !p.state.finished && p.state.currentNum >= p.config.max {
p.state.finished = true
if !p.config.clearOnFinish {
renderProgressBar(p.config, p.state)
}
if p.config.onCompletion != …
```
=> Prevent changing current maximum on Finish

progressbar.go
with the progressbar writing to stderr, when redirecting stdout to a file, the progressbar wasn't stretching to the whole line, limited at 80 columns.
=> try to get stderr width if stdout is not a terminal

progressbar.go, progressbar_test.go
When max is set to `-1`, a spiner is printed. But only first few got displayed.
```go
bar := progressbar.NewOptions(-1,
progressbar.OptionSetDescription("issue"),
progressbar.OptionSetRenderBlankState(true),
progressbar.OptionSpinnerType(15), // rolling a,b,c,d....
progressbar.OptionClearOnFinish())
for !bar.IsFinished() {
_ = bar.Add(1)
println() // print on a dedicate line
time.Sleep(100 * time.Millisecond)
}
```
Sample output:
```
a issue  
b issue  
c issue  
d issue  
e issue  
a issue  
b issue  
c issue  
d issue  
e issue  
a issue  
....
```
default spinner (which is No. 9) has four icons: `| / - \`, \
with original implementation, after 1 second, the `counterTime` is rolled back to now() by `Add64()`, and will take icon at index `(0 / 100) % 4 = 0`, that is `|`.
with this pull …
=> bug fix: spinner only show first few icons

progressbar.go
Set64 func should use currentBytes, not currentNum
Signed-off-by: Jim Ma <majinjing3@gmail.com>
=> Fix Set64 not use currentBytes issue

progressbar.go
When using the progress bar to download files, it will repeatedly render extra empty lines, which is very unfriendly
=> fixed duplicate rendering of extra empty lines

progressbar.go, progressbar_test.go
See my comment here: https://github.com/schollz/progressbar/issues/108#issuecomment-1189221700
The original PR is/was wrong in that it mixes up `os.Stdout` and `os.Stderr` which might appear to produce the correct behaviour until you use some shell redirection to send one of those two outputs somewhere other than the controlling terminal.
If the progress bar is writing to `os.Stderr` then that final newline should also be sent to the same destination; the code was originally correct.
This PR reverts the original commit made in #113 but before I did that, I updated the two tests that use `DefaultBytes()` to ensure that nothing ever gets written to `os.Stdout` by the progress bar code.  These tests obviously fail initially, but then pass with the reverted commit.
=> Revert PR #113

progressbar.go, progressbar_test.go
Bit of a micro-optimization but I noticed that `clearProgressBar` was causing triple `\r` to be emitted unnecessarily.
=> Remove superfluous carriage returns

progressbar.go, progressbar_test.go
Fix for #81.
Clear `lastShown` when using `OptionSetRenderBlankState(true)` or calling `RenderBlank` to force a render.
`Describe` function still honors throttling if enabled.
=> Fix RenderBlank when throttled

progressbar.go, progressbar_test.go
I'd like to support both B/s and GB/s file rates as well. This PR uses the existing `humanizeBytes` function when formatting `averateRate` instead of just hard coding kB and MB.
=> Use the existing humanize function to support GB/s rates

progressbar.go, progressbar_test.go
Currently, the elapsed time is not output if a progress bar is created with length 0. This PR adds the elapsed time to the end of the progress bar in a similar way to a standard progress bar.
This PR also adds `OptionSetElapsedTime` which allows for hiding the elapsed time.
Example:
```
(5/-, 5 it/s) [1s]
```
Let me know if this should be considered a breaking change. I could then change `elapsedTime` to default to `false`.
Thank you!
=> Show elapsed time when no length is given

go.mod, go.sum, progressbar.go
The package `golang.org/x/crypto/ssh/terminal` has been deprecated and replaced with `golang.org/x/term`. This switches to the replacement.
=> Use golang.org/x/term replacement instead of deprecated package

progressbar.go, progressbar_test.go
Below comparison between examples/basic bar output and the output for code on issue schollz/progressbar#130 with the PR changes.
Resolves schollz/progressbar#130
=> feat: on clear, correctly flush with carriage return

progressbar.go, progressbar_test.go
Add an option to keep the render of time elapsed when the bar has finished.
```go
bar := progressbar.NewOptions64(
10,
)
// Output:
//  100% |████████████████████████████████████████|         
bar := progressbar.NewOptions64(
10,
progressbar.OptionShowElapsedTimeOnFinish(),
)
// Output:
//  100% |████████████████████████████████████████|  [10s]
```
Resolves schollz/progressbar#128
=> feat: option to keep showing elapsed time on finish

progressbar.go, progressbar_test.go
This fixes #86 
Hi, I've added the flag `showDescriptionAtLineEnd` to the progress bar. I'm not sure, if I am happy with this naming, but it was the best that came into my mind. :)
The part starting at line 828 is quite cluttered now. I suggest, extracting a function with early returns, but I did not wanted to let this pull request getting too big. If you agree, I can create another pull request for this refactoring.
=> #86 Add option to write description at end of line instead of begin of line

progressbar.go
Issue #75 
Bar was incorrectly being cleared when p.config.useANSICodes == true, but p.config.clearOnFinish == false.
=> Fixes case where bar was being incorrectly cleared on finished #75

progressbar.go, progressbar_test.go
Hi, just thought this might be a small improvement to avoid copying the string over and over with +=.
Nice progress bar btw, thanks very much for it, using it in some of my projects here and there! )
=> Use strings.Builder for bar string composition

.github/workflows/ci.yml, progressbar_test.go
It appears `go vet` isn't particularly happy about some example names in tests:
```
progressbar$ go vet .
./progressbar_test.go:125:1: ExampleOptionShowCountBigNumber refers to unknown identifier: OptionShowCountBigNumber
./progressbar_test.go:146:1: ExampleOptionShowDescriptionAtLineEnd_WithSpinner refers to unknown field or method: OptionShowDescriptionAtLineEnd.WithSpinner
./progressbar_test.go:163:1: ExampleOptionChangeMax refers to unknown identifier: OptionChangeMax
./progressbar_test.go:171:1: ExampleIgnoreLength_WithIteration refers to unknown identifier: IgnoreLength
./progressbar_test.go:233:1: ExampleIgnoreLength_WithSpeed refers to unknown identifier: IgnoreLength
```
This change fixes it and adds `go vet` to the CI workflow.
=> Make go vet happy

progressbar.go, progressbar_test.go
It wasn't very clear whether the full width mode works as expected with different combinations of options, especially those that were added more recently. This change slightly improves formatting in full width mode and also adds a few test cases for it.
=> Add minor fix for full width mode

progressbar.go, progressbar_test.go
I noticed that when running `go test -bench.` it handles stdout and stderr in some different way, so `term.GetSize()` manages to get the actual size of the current terminal and cause TestOptionFullWidth to fail, so here is the fix.
There was also another test that wasn't actually checking anything and I fixed that one as well.
=> Fix full width test

go.mod, go.sum
=> fix: remove github.com/rivo/uniseg from go.mod to fix go version

progressbar.go
Signed-off-by: Keming <kemingy94@gmail.com>
Since `render` is not thread-safe, and `Describe` is provided to update the description.
=> fix data race in `Describe`

go.mod, go.sum, progressbar.go
As commented in #97 , there seemed to be an issue with counting the width of the `█` symbol.
By changing the library used to obtain the width, it seems the problem can be resolved, so I've made the necessary adjustments.
As far as I can check on my end, there doesn't seem to be any issues. However, please check. :pray:
=> change library to get rune width

progressbar.go, progressbar_test.go
Problem: currently `progressbar` uses [SI units](https://en.wikipedia.org/wiki/Binary_prefix) by default:
https://github.com/schollz/progressbar/blob/3d122971646c65a9eff62c04531ec131ffb7ce5a/progressbar.go#L1069
...but calculates them with base `1024`, which is not correct and should be `1000` instead.
It's also not possible to choose which the units to use, e.g. the `github.com/dustin/go-humanize` package, for example, allows one to either use [`Bytes()`](https://pkg.go.dev/github.com/dustin/go-humanize#Bytes) or [`IBytes()`](https://pkg.go.dev/github.com/dustin/go-humanize#IBytes).
Solution: fix SI unit base and introduce `OptionUseIECUnits()` option to enable IEC units like `KiB`, `MiB`, etc.
=> Fix SI units calculation and introduce OptionUseIECUnits()

progressbar.go, progressbar_test.go
Add Current num (as an int not a float), maximum and description to the
State output, hopefully making it a more complete and useful description of the
current state of the bar.
=> Add more properties to State

progressbar.go
RenderBlank() calls render() which requires the mutex to be held. IsFinished accesses p.state, which also requires the mutex to be held.
=> fix: Protect RenderBlank() and IsFinished() with the lock

progressbar.go
=> fix error return

progressbar.go
The Go Race Detector pointed out a data race between
the methods ChangeMax64 and State or GetMax64.
State already takes the lock, but others did not.
=> fix race condition when changing max

progressbar.go, progressbar_test.go
Display elapsed time at the end of the bar when elapsedTime is enabled while predictTime is set to false.
To avoid breaking changes, the default value of the elapsed time option is changed to false in non-spinner mode.
Demo:
```
70% |███████   |  [0s]
```
=> fix: make elapsedTime option work in non-spinner mode

progressbar.go, progressbar_test.go
#187 
I apologize for the oversight in #182 regarding the spinner scenario.
For spinner types, we should not call `Set(max)` in `Finish()` because:
1. The spinner's max is set to the width, so calling `Set(max)` results in incorrect `currentBytes`.
2. In `Add(num)`, if `currentNum < max`, `currentNum = (currentNum + num) % max`, preventing the spinner from finishing.
A simple solution is to update `currentBytes` for non-spinners.
=> fix: only fill the bar for spinners in Finish()

.github/workflows/golangci-lint.yml, .golangci.yml
Hi @schollz 
Generally, we use automated linters to keep the basic sanity in code base. 
So, I am proposing some basic linters for this repo using GitHub Actions. 
Feel free to suggest changes if needed. 
Following are the basic linters introduced using[ golangci-lint](https://golangci-lint.run) tool.
```
- errcheck
- gocyclo
- gofmt
- goimports
- gosimple
- govet
- ineffassign
- staticcheck
- unused
```
two of the linters are showing some errors. that can be addressed as separate pr.
=> add golangci linter in github workflow action

progressbar.go
Hello, I've added `Bprint...` functions to correctly print text to config.writer while the progress bar is active.
=> add support for print text during render progress bar

progressbar.go
Hey!
I've been testing the new `Bprintf` and `Bprintln` functions, and have found a race condition.
If text is printed at the same time as `Write` is called, there's a chance that some of the text will not be printed. This is because `bytes.Buffer` is not thread-safe. In my testing, acquiring a lock in `Bprintf` and `Bprintln` fixes the issue.
=> fix: Acquire lock when printing text to fix race condition

progressbar.go
This pr is created to resolve https://github.com/schollz/progressbar/issues/176.
You can using this new feature like this:
```go
package main
import (
"fmt"
"github.com/schollz/progressbar/v3"
"time"
)
func main(){
bar := progressbar.NewOptions(100,progressbar.OptionSetMaxDetailRow(10))
for i:=1;i<=100;i++{
bar.AddDetail(fmt.Sprint("processing... ",i))
if i%10==0{
bar.Add(10)
}
time.Sleep(100*time.Millisecond)
}
}
```
output would be:
in the end:
I use ANSI to solve this problem,which makes it easy for me to control the cursor of terminal. I avoid make the progressbar and detail a whole string to update the detail though it may cause difficulties. According to my own experience, the detail of progress has the update frequency which is much higher then progress bar. So it is better to make …
=> Feature scrolling detail

progressbar.go, progressbar_test.go
It's the pr to resolve https://github.com/schollz/progressbar/issues/195.
=> fix: change some attribute about time to time.Time{}

progressbar.go
fix https://github.com/schollz/progressbar/issues/147. And more explanation can be seen at pr https://github.com/schollz/progressbar/pull/192 ,which was accidentally closed by me.🥲
=> fix:fixed the bug that changMax isn't working.

progressbar.go, progressbar_test.go
- Added BarStartFilled and BarEndFilled fields to Theme struct, and corresponding unit tests.
- Added 3 predefined themes for users to choose from, if they want: ThemeDefault (no changes), ThemeASCII ("[===>...]") and ThemeUnicode using graphic symbols. 
- Small documentation additions and fixes.
- Fixed issue where a call to ProgressBar.Finish() after it had already been finished by ProgressBar.Add(), would clear it, even if the user didn't request the clear.
Following up on issue #203
=> Added BarStartFilled and BarEndFille to Theme struct #203

progressbar.go, progressbar_test.go
Fixes #40
Note that the [proposed workaround in the #40](https://github.com/schollz/progressbar/issues/40#issuecomment-612444849) has a race condition--hence why this atomic operation is necessary.
=> add AddMax

go.mod, progressbar.go, progressbar_test.go
Users now can monitor status updates in status bar via `xbar` extension or other UI components.
demo `xbar` extension:
`progress_monitor.1s.sh`:
```shell
#!/bin/bash
curl -s "http://x.x.x.x:19999/desc"
```
status bar demo:
=> feat: add an HTTP server to enable users to monitor status updates via status bars or other UI components.

go.sum, progressbar.go, progressbar_test.go
This PR refactors the HTTP server implementation in the ProgressBar to address issues with the global default HTTP server instance, which caused panics when creating multiple ProgressBar instances with HTTP servers. The changes introduce a dedicated HTTP server instance for each ProgressBar, enabling users to safely run and manage multiple servers.
Replaced the global http.HandleFunc with isolated http.ServeMux instances per ProgressBar.
Added a new HTTPServer object returned by StartHTTPServer(), providing a Shutdown() method for graceful termination.
Prevents route conflicts between multiple ProgressBar instances.
Allows users to start and stop HTTP servers independently.
Ensures safer concurrent usage and better resource management.
=> feat: allow user to safely run and manage multiple progressbar http servers

progressbar.go
fix: https://github.com/schollz/progressbar/issues/212
when user do not add detail, the progress bar will panic because index out of range.
=> fix: when setMaxDetailRow() but not use AddDetail(), cause index out of range.

progressbar.go, progressbar_test.go
Instead of always checking stdout, check the actually configured output file. Fixes cases when stdout is redirected to a file or /dev/null, but stderr remains connected to the terminal.
It was previously fixed in #91, but was broken in #156.
=> Fix terminal width when stdout is redirected
